### ISSUE TITLE
v0.29 beta3 - "Lives" extend beyond 0 and max, both visually and literally.

### ISSUE THREAD

**Issue by Kappatalist** [ExPorygon/Ephemeral-Unnatural-Balance#48]
Get an extend while already at max lives? You still get the extend, and the lives display gains an extra star.
Lose your last life? You still respawn. Upon dying again, you'll get a "negative" star, and then game over. In once instance, I was able to gain two negative stars, then the game proceeded without respawning the player character.

**Comment by ExPorygon** [comment]
Part of this should be fixed. Stages 2 and 3 should as of d23f24d66fb2a1aac086082a5ce8a6f025dbd36a properly cause gameovers when out of lives. The visual aspect is decidedly minor and will be likely fixed at a later time.

**Comment by Sparen** [comment]
Still occurs when all lives are gone. (as of 3f34463f869df7c6b0ffcca7c38f10847a36068b)

**Comment by Sparen** [comment]
Still present as of cd5b6795528eed22eaa35cc7499e9fe936d8d301 (Version 0.32)
